export const HOURS_OPTIONS = [
  { label: "30 минут", value: "0.5" },
  { label: "1 час", value: "1" },
  { label: "1 час 30 минут", value: "1.5" },
  { label: "2 часа", value: "2" },
  { label: "2 часа 30 минут", value: "2.5" },
  { label: "3 часа", value: "3" },
  { label: "3 часа 30 минут", value: "3.5" },
  { label: "4 часа", value: "4" },
  { label: "4 часа 30 минут", value: "4.5" },
  { label: "5 часов", value: "5" },
  { label: "5 часов 30 минут", value: "5.5" },
  { label: "6 часов", value: "6" },
  { label: "6 часов 30 минут", value: "6.5" },
  { label: "7 часов", value: "7" },
  { label: "7 часов 30 минут", value: "7.5" },
  { label: "8 часов", value: "8" },
  { label: "9 часов", value: "9" },
  { label: "10 часов", value: "10" },
  { label: "11 часов", value: "11" },
  { label: "12 часов", value: "12" },
  { label: "13 часов", value: "13" },
  { label: "14 часов", value: "14" },
  { label: "15 часов", value: "15" },
  { label: "16 часов", value: "16" },
  { label: "17 часов", value: "17" },
  { label: "18 часов", value: "18" },
  { label: "19 часов", value: "19" },
  { label: "20 часов", value: "20" },
  { label: "21 час", value: "21" },
  { label: "22 часа", value: "22" },
  { label: "23 часа", value: "23" },
  { label: "24 часа", value: "24" },
] as const;
